export  {default as Header} from '../components/header/Header'
export  {default as Service} from '../components/service/Service'
export  {default as About} from '../components/about/About'
export  {default as Contact} from '../components/contact/Contact'
export  {default as Footer} from '../components/footer/Footer'